
## For Orignal Transformation - Data Pre-processing 
DEFAULT_DATASET_TRANSFORM_TYPE = "augmented"
DEFAULT_ORIGNAL_TRANSFORM_RESIZE = (224, 224)
DEFAULT_ORIGNAL_NORMALIZE_MEAN = [0.485, 0.456, 0.406]
DEFAULT_ORIGNAL_NORMALIZE_STD = [0.229, 0.224, 0.225]

## For Augmented Transformation - Data Pre-processing 
DEFAULT_AUGMENTED_TRANSFORM_RESIZE = (224, 224)
DEFAULT_AUGMENTED_RANDOM_HORIZONTAL_FLIP = 1.0
DEFAULT_AUGMENTED_RANDOM_ROTATION = 15
DEFAULT_AUGMENTED_NORMALIZE_MEAN = [0.485, 0.456, 0.406]
DEFAULT_AUGMENTED_NORMALIZE_STD = [0.229, 0.224, 0.225]

## For Generating Train-val-test split
TRAIN_SET_SIZE = 0.7 # Train set size
TEST_SET_SIZE = 0.15 # Test set size
RANDOM_SEED = 42 # Random state for shuffle in train_test_split

## FOR Learning Rate Scheduler
LR_SCHEDULER_FACTOR = 0.1
LR_SCHEDULER_THRESHOLD = 0.0001
LR_SCHEDULER_COOLDOWN = 0
LR_SCHEDULER_MIN_LR = 0
LR_SCHEDULER_EPSILON = 1e-8


## FOR CNN MODEL
CNN_BATCH_SIZE = 16
CNN_DROPOUT_RATE = 0.5
CNN_FC_UNITS = 64
CNN_EPOCHS = 10
CNN_ES_PATIENCE = 5
CNN_LR_SCHEDULER_PATIENCE = 7

